A_LAMP	EQU		P2
EW_G	EQU		01100110B
A_RED	EQU		11111111B
LEN_GR	EQU		25H
LEN_SP	EQU		5H
		ORG		0000H
		LJMP	START
		ORG		0003H
		LJMP	INT0_S
		ORG		0030H
START:	MOV		SP,#60H
		LCALL	INIT
MLOOP:	MOV		R5,#LEN_GR
		LCALL	DELAY
		XRL		A_LAMP,#0FFH
		SJMP	MLOOP
INIT:	MOV		A_LAMP,#EW_G
		SETB	IT0
		SETB	EX0
		SETB	EA
		RET
DELAY:	MOV		R7,#00H
		MOV		R6,#00H
LOOP:	DJNZ	R7,LOOP
		DJNZ	R6,LOOP
		DJNZ	R5,LOOP
		RET
INT0_S:	CLR		EA
		PUSH	PSW
		MOV		A,A_LAMP
		PUSH	ACC
		CLR		RS1
		SETB	RS0
		SETB	EA
		MOV		A_LAMP,#A_RED
		MOV		R1,#0AH
T:		MOV		R5,#LEN_SP
		LCALL	DELAY
		XRL		A_LAMP,#0FFH
		DJNZ	R1,T
		CLR		EA
		POP		ACC
		MOV		A_LAMP,A
		POP		PSW
		SETB	EA
		RETI
		END