T1MOD_W	EQU	00100000B
			;GATE1=0
			;C/T1=0
			;M1=1,M0=0
BPS_I	EQU	0FDH
COMM	DATA	070H
FLAG	BIT		00H
A_LAMP	EQU		P2
E_G_D	EQU		01101010B
W_G_D	EQU		10100110B
S_G_D	EQU		10011010B
N_G_D	EQU		10101001B
		ORG		0000H
		LJMP	START
		ORG		0023H
		LJMP	RS232_S
		ORG		0030H
START:	LCALL	INIT
MLOOP:	CLR		FLAG
LOOP:	JNB		FLAG,LOOP
		MOV		A,COMM
		CJNE	A,#'0',N_C1
		MOV		A,#00H
		LCALL	DISP
	    SJMP	MLOOP
N_C1:	CJNE	A,#'1',N_C2
		MOV		A,#01H
		LCALL	DISP
	    SJMP	MLOOP
N_C2:	CJNE	A,#'2',N_C3
		MOV		A,#02H
		LCALL	DISP
	    SJMP	MLOOP
N_C3:	CJNE	A,#'3',N_C4
		MOV		A,#03H
		LCALL	DISP
	    SJMP	MLOOP
N_C4:	CJNE	A,#'4',N_C5
		MOV		A,#04H
		LCALL	DISP
	    SJMP	MLOOP
N_C5:	CJNE	A,#'5',N_C6
		MOV		A,#05H
		LCALL	DISP
	    SJMP	MLOOP
N_C6:	CJNE	A,#'6',N_C7
		MOV		A,#06H
		LCALL	DISP
	    SJMP	MLOOP
N_C7:	CJNE	A,#'7',N_C8
		MOV		A,#07H
		LCALL	DISP
	    SJMP	MLOOP
N_C8:	CJNE	A,#'8',N_C9
		MOV		A,#08H
		LCALL	DISP
	    SJMP	MLOOP
T:		SJMP	MLOOP
N_C9:	CJNE	A,#'9',N_CA
		MOV		A,#09H
		LCALL	DISP
	    SJMP	MLOOP
N_CA:	CJNE	A,#'A',N_CB
		MOV		A,#0AH
		LCALL	DISP
	    SJMP	MLOOP
N_CB:	CJNE	A,#'B',N_CC
		MOV		A,#0BH
		LCALL	DISP
	    SJMP	T
N_CC:	CJNE	A,#'C',N_CD
		MOV		A,#0CH
		LCALL	DISP
	    SJMP	T
N_CD:	CJNE	A,#'D',N_CE
		MOV		A,#0DH
		LCALL	DISP
	    SJMP	T
N_CE:	CJNE	A,#'E',N_CF
		MOV		A,#0EH
		LCALL	DISP
	    SJMP	T
N_CF:	CJNE	A,#'F',N_CF
		MOV		A,#0FH
		LCALL	DISP
	    SJMP	T
EL:		CLR		T1
		SJMP	T
INIT:	SETB	SM0
		SETB	SM1
		SETB	REN
		MOV		TMOD,#T1MOD_W
		MOV		TH1,#BPS_I
		MOV		TL1,#BPS_I
		SETB	TR1
		SETB	ES
		SETB	EA
		RET
RS232_S:
		JNB		TI,RECE
		CLR		TI
		RETI
RECE:	MOV		A,SBUF
		JNB		P,P_Z
		JNB		RB8,ERROR
		SJMP	RIGHT
P_Z:	JB		RB8,ERROR
RIGHT:	MOV		COMM,A
		MOV		A,#'Y'
		MOV		SBUF,A
		SETB	FLAG
		CLR		RI
		RETI
ERROR:	MOV		A,#'N'
		MOV		SBUF,A
		CLR		FLAG
		CLR		RI
		RETI
DISP:	MOV		DPTR,#WTAB
		MOVC	A,@A+DPTR
		MOV		A_LAMP,	A
		RET
WTAB:	DB		0C0H,0F9H,0A4H,0B0H
		DB		099H,092H,082H,0F8H
		DB		080H,090H,088H,083H
		DB		0C6H,0A1H,086H,08EH
		END